services:
  # Web Service
  - type: web
    name: reforestgo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ReforestGo.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: reforestgo-db
          property: connectionString

databases:
  - name: reforestgo-db
    databaseName: reforestgo
    user: reforestgo